/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"
#include <iostream>
#include <spdlog/spdlog.h>
#include "../utils/ArrayUtils.h"
#include "utils/MaxwellBoltzmannDistribution.h"

Particle::Particle(int type_arg) {
    type = type_arg;
    if (auto logger = spdlog::get("default"); logger) {
        SPDLOG_LOGGER_DEBUG(logger, "Particle generated!");
    }
    f = {0., 0., 0.};
    old_f = {0., 0., 0.};
}

Particle::Particle(const Particle &other) {
    x = other.x;
    v = other.v;
    f = other.f;
    old_f = other.old_f;
    m = other.m;
    eps = other.eps;
    sig = other.sig;
    type = other.type;
    state = other.state;
    if (auto logger = spdlog::get("default"); logger) {
        SPDLOG_LOGGER_DEBUG(logger, "Particle generated by copy!");
    }
}


Particle::Particle(std::array<double, 3> x_arg, std::array<double, 3> v_arg, double m_arg, double eps_arg,
                   double sig_arg, int type_arg, int state_arg) {
    x = x_arg;
    v = v_arg;
    m = m_arg;
    eps = eps_arg;
    sig = sig_arg;
    type = type_arg;
    state = state_arg;
    f = {0., 0., 0.};
    old_f = {0., 0., 0.};
    if (auto logger = spdlog::get("default"); logger) {
        SPDLOG_LOGGER_DEBUG(logger, "Particle generated!");
    }
}

Particle::~Particle() {
}

const std::array<double, 3> &Particle::getX() const { return x; }

void Particle::setX(const std::array<double, 3> &x_arg) { x = x_arg; }

const std::array<double, 3> &Particle::getV() const { return v; }

void Particle::setV(const std::array<double, 3> &v_arg) { v = v_arg; }

const std::array<double, 3> &Particle::getF() const { return f; }

void Particle::setF(const std::array<double, 3> &f_arg) { f = f_arg; }

const std::array<double, 3> &Particle::getOldF() const { return old_f; }

void Particle::setOldF(const std::array<double, 3> &old_f_arg) { old_f = old_f_arg; }

double Particle::getM() const { return m; }

double Particle::getEps() const { return eps; }

double Particle::getSig() const { return sig; }

int Particle::getType() const { return type; }

int Particle::getState() const { return state; }

void Particle::setState(int state_arg) { state = state_arg; }

std::string Particle::toString() const {
    std::stringstream stream;
    stream << "Particle: X:" << x << " v: " << v << " f: " << f
            << " old_f: " << old_f << " type: " << type;
    return stream.str();
}

bool Particle::operator==(Particle &other) {
    return (x == other.x) and (v == other.v) and (f == other.f) and
           (type == other.type) and (m == other.m) and (old_f == other.old_f);
}

bool Particle::operator==(const Particle &other) const {
    return (x == other.x) and (v == other.v) and (f == other.f) and
           (type == other.type) and (m == other.m) and (old_f == other.old_f);
}

std::ostream &operator<<(std::ostream &stream, Particle &p) {
    stream << p.toString();
    return stream;
}

bool particle_sem_eq(const Particle &p1, const Particle &p2) {
    if ((p1.getM() != p2.getM()) || (p1.getType() != p2.getType())) {
        return false;
    }
    for (int i = 0; i < 3; i++) {
        if ((p1.getX()[i] != p2.getX()[i]) ||
            (p1.getV()[i] != p2.getV()[i]) ||
            (p1.getV()[i] != p2.getF()[i]) ||
            (p1.getOldF()[i] != p2.getOldF()[i])) {
            return false;
        }
    }
    return true;
}
