// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "input.h"

// Molsim_Input
// 

const Molsim_Input::Parameters_type& Molsim_Input::
Parameters () const
{
  return this->Parameters_.get ();
}

Molsim_Input::Parameters_type& Molsim_Input::
Parameters ()
{
  return this->Parameters_.get ();
}

void Molsim_Input::
Parameters (const Parameters_type& x)
{
  this->Parameters_.set (x);
}

void Molsim_Input::
Parameters (::std::unique_ptr< Parameters_type > x)
{
  this->Parameters_.set (std::move (x));
}

const Molsim_Input::Particles_type& Molsim_Input::
Particles () const
{
  return this->Particles_.get ();
}

Molsim_Input::Particles_type& Molsim_Input::
Particles ()
{
  return this->Particles_.get ();
}

void Molsim_Input::
Particles (const Particles_type& x)
{
  this->Particles_.set (x);
}

void Molsim_Input::
Particles (::std::unique_ptr< Particles_type > x)
{
  this->Particles_.set (std::move (x));
}


// Parameters
// 

const Parameters::delta_t_type& Parameters::
delta_t () const
{
  return this->delta_t_.get ();
}

Parameters::delta_t_type& Parameters::
delta_t ()
{
  return this->delta_t_.get ();
}

void Parameters::
delta_t (const delta_t_type& x)
{
  this->delta_t_.set (x);
}

Parameters::delta_t_type Parameters::
delta_t_default_value ()
{
  return delta_t_type (.0002);
}

const Parameters::t_end_type& Parameters::
t_end () const
{
  return this->t_end_.get ();
}

Parameters::t_end_type& Parameters::
t_end ()
{
  return this->t_end_.get ();
}

void Parameters::
t_end (const t_end_type& x)
{
  this->t_end_.set (x);
}

Parameters::t_end_type Parameters::
t_end_default_value ()
{
  return t_end_type (5.0);
}

const Parameters::box_size_type& Parameters::
box_size () const
{
  return this->box_size_.get ();
}

Parameters::box_size_type& Parameters::
box_size ()
{
  return this->box_size_.get ();
}

void Parameters::
box_size (const box_size_type& x)
{
  this->box_size_.set (x);
}

void Parameters::
box_size (::std::unique_ptr< box_size_type > x)
{
  this->box_size_.set (std::move (x));
}

const Parameters::number_cells_type& Parameters::
number_cells () const
{
  return this->number_cells_.get ();
}

Parameters::number_cells_type& Parameters::
number_cells ()
{
  return this->number_cells_.get ();
}

void Parameters::
number_cells (const number_cells_type& x)
{
  this->number_cells_.set (x);
}

void Parameters::
number_cells (::std::unique_ptr< number_cells_type > x)
{
  this->number_cells_.set (std::move (x));
}

const Parameters::boundary_conditions_type& Parameters::
boundary_conditions () const
{
  return this->boundary_conditions_.get ();
}

Parameters::boundary_conditions_type& Parameters::
boundary_conditions ()
{
  return this->boundary_conditions_.get ();
}

void Parameters::
boundary_conditions (const boundary_conditions_type& x)
{
  this->boundary_conditions_.set (x);
}

void Parameters::
boundary_conditions (::std::unique_ptr< boundary_conditions_type > x)
{
  this->boundary_conditions_.set (std::move (x));
}

const Parameters::cutoff_type& Parameters::
cutoff () const
{
  return this->cutoff_.get ();
}

Parameters::cutoff_type& Parameters::
cutoff ()
{
  return this->cutoff_.get ();
}

void Parameters::
cutoff (const cutoff_type& x)
{
  this->cutoff_.set (x);
}

Parameters::cutoff_type Parameters::
cutoff_default_value ()
{
  return cutoff_type (3.0);
}

const Parameters::writer_type& Parameters::
writer () const
{
  return this->writer_.get ();
}

Parameters::writer_type& Parameters::
writer ()
{
  return this->writer_.get ();
}

void Parameters::
writer (const writer_type& x)
{
  this->writer_.set (x);
}

void Parameters::
writer (::std::unique_ptr< writer_type > x)
{
  this->writer_.set (std::move (x));
}

const Parameters::writer_type& Parameters::
writer_default_value ()
{
  return writer_default_value_;
}

const Parameters::force_type& Parameters::
force () const
{
  return this->force_.get ();
}

Parameters::force_type& Parameters::
force ()
{
  return this->force_.get ();
}

void Parameters::
force (const force_type& x)
{
  this->force_.set (x);
}

void Parameters::
force (::std::unique_ptr< force_type > x)
{
  this->force_.set (std::move (x));
}

const Parameters::force_type& Parameters::
force_default_value ()
{
  return force_default_value_;
}

const Parameters::output_name_type& Parameters::
output_name () const
{
  return this->output_name_.get ();
}

Parameters::output_name_type& Parameters::
output_name ()
{
  return this->output_name_.get ();
}

void Parameters::
output_name (const output_name_type& x)
{
  this->output_name_.set (x);
}

void Parameters::
output_name (::std::unique_ptr< output_name_type > x)
{
  this->output_name_.set (std::move (x));
}

const Parameters::output_name_type& Parameters::
output_name_default_value ()
{
  return output_name_default_value_;
}

const Parameters::output_frequency_type& Parameters::
output_frequency () const
{
  return this->output_frequency_.get ();
}

Parameters::output_frequency_type& Parameters::
output_frequency ()
{
  return this->output_frequency_.get ();
}

void Parameters::
output_frequency (const output_frequency_type& x)
{
  this->output_frequency_.set (x);
}

Parameters::output_frequency_type Parameters::
output_frequency_default_value ()
{
  return output_frequency_type (50LL);
}


// Particles
// 

const Particles::cuboid_sequence& Particles::
cuboid () const
{
  return this->cuboid_;
}

Particles::cuboid_sequence& Particles::
cuboid ()
{
  return this->cuboid_;
}

void Particles::
cuboid (const cuboid_sequence& s)
{
  this->cuboid_ = s;
}

const Particles::particle_sequence& Particles::
particle () const
{
  return this->particle_;
}

Particles::particle_sequence& Particles::
particle ()
{
  return this->particle_;
}

void Particles::
particle (const particle_sequence& s)
{
  this->particle_ = s;
}

const Particles::disc_sequence& Particles::
disc () const
{
  return this->disc_;
}

Particles::disc_sequence& Particles::
disc ()
{
  return this->disc_;
}

void Particles::
disc (const disc_sequence& s)
{
  this->disc_ = s;
}


// box_size
// 

const box_size::x_size_type& box_size::
x_size () const
{
  return this->x_size_.get ();
}

box_size::x_size_type& box_size::
x_size ()
{
  return this->x_size_.get ();
}

void box_size::
x_size (const x_size_type& x)
{
  this->x_size_.set (x);
}

box_size::x_size_type box_size::
x_size_default_value ()
{
  return x_size_type (3.0);
}

const box_size::y_size_type& box_size::
y_size () const
{
  return this->y_size_.get ();
}

box_size::y_size_type& box_size::
y_size ()
{
  return this->y_size_.get ();
}

void box_size::
y_size (const y_size_type& x)
{
  this->y_size_.set (x);
}

box_size::y_size_type box_size::
y_size_default_value ()
{
  return y_size_type (3.0);
}

const box_size::z_size_type& box_size::
z_size () const
{
  return this->z_size_.get ();
}

box_size::z_size_type& box_size::
z_size ()
{
  return this->z_size_.get ();
}

void box_size::
z_size (const z_size_type& x)
{
  this->z_size_.set (x);
}

box_size::z_size_type box_size::
z_size_default_value ()
{
  return z_size_type (1.0);
}


// number_cells
// 

const number_cells::x_number_type& number_cells::
x_number () const
{
  return this->x_number_.get ();
}

number_cells::x_number_type& number_cells::
x_number ()
{
  return this->x_number_.get ();
}

void number_cells::
x_number (const x_number_type& x)
{
  this->x_number_.set (x);
}

number_cells::x_number_type number_cells::
x_number_default_value ()
{
  return x_number_type (1LL);
}

const number_cells::y_number_type& number_cells::
y_number () const
{
  return this->y_number_.get ();
}

number_cells::y_number_type& number_cells::
y_number ()
{
  return this->y_number_.get ();
}

void number_cells::
y_number (const y_number_type& x)
{
  this->y_number_.set (x);
}

number_cells::y_number_type number_cells::
y_number_default_value ()
{
  return y_number_type (1LL);
}

const number_cells::z_number_type& number_cells::
z_number () const
{
  return this->z_number_.get ();
}

number_cells::z_number_type& number_cells::
z_number ()
{
  return this->z_number_.get ();
}

void number_cells::
z_number (const z_number_type& x)
{
  this->z_number_.set (x);
}

number_cells::z_number_type number_cells::
z_number_default_value ()
{
  return z_number_type (1LL);
}


// boundary_conditions
// 

const boundary_conditions::top_bound_type& boundary_conditions::
top_bound () const
{
  return this->top_bound_.get ();
}

boundary_conditions::top_bound_type& boundary_conditions::
top_bound ()
{
  return this->top_bound_.get ();
}

void boundary_conditions::
top_bound (const top_bound_type& x)
{
  this->top_bound_.set (x);
}

void boundary_conditions::
top_bound (::std::unique_ptr< top_bound_type > x)
{
  this->top_bound_.set (std::move (x));
}

const boundary_conditions::top_bound_type& boundary_conditions::
top_bound_default_value ()
{
  return top_bound_default_value_;
}

const boundary_conditions::right_bound_type& boundary_conditions::
right_bound () const
{
  return this->right_bound_.get ();
}

boundary_conditions::right_bound_type& boundary_conditions::
right_bound ()
{
  return this->right_bound_.get ();
}

void boundary_conditions::
right_bound (const right_bound_type& x)
{
  this->right_bound_.set (x);
}

void boundary_conditions::
right_bound (::std::unique_ptr< right_bound_type > x)
{
  this->right_bound_.set (std::move (x));
}

const boundary_conditions::right_bound_type& boundary_conditions::
right_bound_default_value ()
{
  return right_bound_default_value_;
}

const boundary_conditions::bottom_bound_type& boundary_conditions::
bottom_bound () const
{
  return this->bottom_bound_.get ();
}

boundary_conditions::bottom_bound_type& boundary_conditions::
bottom_bound ()
{
  return this->bottom_bound_.get ();
}

void boundary_conditions::
bottom_bound (const bottom_bound_type& x)
{
  this->bottom_bound_.set (x);
}

void boundary_conditions::
bottom_bound (::std::unique_ptr< bottom_bound_type > x)
{
  this->bottom_bound_.set (std::move (x));
}

const boundary_conditions::bottom_bound_type& boundary_conditions::
bottom_bound_default_value ()
{
  return bottom_bound_default_value_;
}

const boundary_conditions::left_bound_type& boundary_conditions::
left_bound () const
{
  return this->left_bound_.get ();
}

boundary_conditions::left_bound_type& boundary_conditions::
left_bound ()
{
  return this->left_bound_.get ();
}

void boundary_conditions::
left_bound (const left_bound_type& x)
{
  this->left_bound_.set (x);
}

void boundary_conditions::
left_bound (::std::unique_ptr< left_bound_type > x)
{
  this->left_bound_.set (std::move (x));
}

const boundary_conditions::left_bound_type& boundary_conditions::
left_bound_default_value ()
{
  return left_bound_default_value_;
}


// cuboid
// 

const cuboid::base_coordinates_type& cuboid::
base_coordinates () const
{
  return this->base_coordinates_.get ();
}

cuboid::base_coordinates_type& cuboid::
base_coordinates ()
{
  return this->base_coordinates_.get ();
}

void cuboid::
base_coordinates (const base_coordinates_type& x)
{
  this->base_coordinates_.set (x);
}

void cuboid::
base_coordinates (::std::unique_ptr< base_coordinates_type > x)
{
  this->base_coordinates_.set (std::move (x));
}

const cuboid::number_particles_type& cuboid::
number_particles () const
{
  return this->number_particles_.get ();
}

cuboid::number_particles_type& cuboid::
number_particles ()
{
  return this->number_particles_.get ();
}

void cuboid::
number_particles (const number_particles_type& x)
{
  this->number_particles_.set (x);
}

void cuboid::
number_particles (::std::unique_ptr< number_particles_type > x)
{
  this->number_particles_.set (std::move (x));
}

const cuboid::velocity_type& cuboid::
velocity () const
{
  return this->velocity_.get ();
}

cuboid::velocity_type& cuboid::
velocity ()
{
  return this->velocity_.get ();
}

void cuboid::
velocity (const velocity_type& x)
{
  this->velocity_.set (x);
}

void cuboid::
velocity (::std::unique_ptr< velocity_type > x)
{
  this->velocity_.set (std::move (x));
}

const cuboid::spacing_type& cuboid::
spacing () const
{
  return this->spacing_.get ();
}

cuboid::spacing_type& cuboid::
spacing ()
{
  return this->spacing_.get ();
}

void cuboid::
spacing (const spacing_type& x)
{
  this->spacing_.set (x);
}

const cuboid::mass_type& cuboid::
mass () const
{
  return this->mass_.get ();
}

cuboid::mass_type& cuboid::
mass ()
{
  return this->mass_.get ();
}

void cuboid::
mass (const mass_type& x)
{
  this->mass_.set (x);
}

const cuboid::brownian_vel_type& cuboid::
brownian_vel () const
{
  return this->brownian_vel_.get ();
}

cuboid::brownian_vel_type& cuboid::
brownian_vel ()
{
  return this->brownian_vel_.get ();
}

void cuboid::
brownian_vel (const brownian_vel_type& x)
{
  this->brownian_vel_.set (x);
}


// particle
// 

const particle::position_type& particle::
position () const
{
  return this->position_.get ();
}

particle::position_type& particle::
position ()
{
  return this->position_.get ();
}

void particle::
position (const position_type& x)
{
  this->position_.set (x);
}

void particle::
position (::std::unique_ptr< position_type > x)
{
  this->position_.set (std::move (x));
}

const particle::velocity_type& particle::
velocity () const
{
  return this->velocity_.get ();
}

particle::velocity_type& particle::
velocity ()
{
  return this->velocity_.get ();
}

void particle::
velocity (const velocity_type& x)
{
  this->velocity_.set (x);
}

void particle::
velocity (::std::unique_ptr< velocity_type > x)
{
  this->velocity_.set (std::move (x));
}

const particle::mass_type& particle::
mass () const
{
  return this->mass_.get ();
}

particle::mass_type& particle::
mass ()
{
  return this->mass_.get ();
}

void particle::
mass (const mass_type& x)
{
  this->mass_.set (x);
}


// disc
// 

const disc::position_type& disc::
position () const
{
  return this->position_.get ();
}

disc::position_type& disc::
position ()
{
  return this->position_.get ();
}

void disc::
position (const position_type& x)
{
  this->position_.set (x);
}

void disc::
position (::std::unique_ptr< position_type > x)
{
  this->position_.set (std::move (x));
}

const disc::velocity_type& disc::
velocity () const
{
  return this->velocity_.get ();
}

disc::velocity_type& disc::
velocity ()
{
  return this->velocity_.get ();
}

void disc::
velocity (const velocity_type& x)
{
  this->velocity_.set (x);
}

void disc::
velocity (::std::unique_ptr< velocity_type > x)
{
  this->velocity_.set (std::move (x));
}

const disc::radius_type& disc::
radius () const
{
  return this->radius_.get ();
}

disc::radius_type& disc::
radius ()
{
  return this->radius_.get ();
}

void disc::
radius (const radius_type& x)
{
  this->radius_.set (x);
}

const disc::mass_type& disc::
mass () const
{
  return this->mass_.get ();
}

disc::mass_type& disc::
mass ()
{
  return this->mass_.get ();
}

void disc::
mass (const mass_type& x)
{
  this->mass_.set (x);
}

const disc::spacing_type& disc::
spacing () const
{
  return this->spacing_.get ();
}

disc::spacing_type& disc::
spacing ()
{
  return this->spacing_.get ();
}

void disc::
spacing (const spacing_type& x)
{
  this->spacing_.set (x);
}

const disc::brownian_vel_type& disc::
brownian_vel () const
{
  return this->brownian_vel_.get ();
}

disc::brownian_vel_type& disc::
brownian_vel ()
{
  return this->brownian_vel_.get ();
}

void disc::
brownian_vel (const brownian_vel_type& x)
{
  this->brownian_vel_.set (x);
}


// base_coordinates
// 

const base_coordinates::x_coordinate_type& base_coordinates::
x_coordinate () const
{
  return this->x_coordinate_.get ();
}

base_coordinates::x_coordinate_type& base_coordinates::
x_coordinate ()
{
  return this->x_coordinate_.get ();
}

void base_coordinates::
x_coordinate (const x_coordinate_type& x)
{
  this->x_coordinate_.set (x);
}

const base_coordinates::y_coordinate_type& base_coordinates::
y_coordinate () const
{
  return this->y_coordinate_.get ();
}

base_coordinates::y_coordinate_type& base_coordinates::
y_coordinate ()
{
  return this->y_coordinate_.get ();
}

void base_coordinates::
y_coordinate (const y_coordinate_type& x)
{
  this->y_coordinate_.set (x);
}

const base_coordinates::z_coordinate_type& base_coordinates::
z_coordinate () const
{
  return this->z_coordinate_.get ();
}

base_coordinates::z_coordinate_type& base_coordinates::
z_coordinate ()
{
  return this->z_coordinate_.get ();
}

void base_coordinates::
z_coordinate (const z_coordinate_type& x)
{
  this->z_coordinate_.set (x);
}


// number_particles
// 

const number_particles::x_number_type& number_particles::
x_number () const
{
  return this->x_number_.get ();
}

number_particles::x_number_type& number_particles::
x_number ()
{
  return this->x_number_.get ();
}

void number_particles::
x_number (const x_number_type& x)
{
  this->x_number_.set (x);
}

const number_particles::y_number_type& number_particles::
y_number () const
{
  return this->y_number_.get ();
}

number_particles::y_number_type& number_particles::
y_number ()
{
  return this->y_number_.get ();
}

void number_particles::
y_number (const y_number_type& x)
{
  this->y_number_.set (x);
}

const number_particles::z_number_type& number_particles::
z_number () const
{
  return this->z_number_.get ();
}

number_particles::z_number_type& number_particles::
z_number ()
{
  return this->z_number_.get ();
}

void number_particles::
z_number (const z_number_type& x)
{
  this->z_number_.set (x);
}


// velocity
// 

const velocity::x_velocity_type& velocity::
x_velocity () const
{
  return this->x_velocity_.get ();
}

velocity::x_velocity_type& velocity::
x_velocity ()
{
  return this->x_velocity_.get ();
}

void velocity::
x_velocity (const x_velocity_type& x)
{
  this->x_velocity_.set (x);
}

const velocity::y_velocity_type& velocity::
y_velocity () const
{
  return this->y_velocity_.get ();
}

velocity::y_velocity_type& velocity::
y_velocity ()
{
  return this->y_velocity_.get ();
}

void velocity::
y_velocity (const y_velocity_type& x)
{
  this->y_velocity_.set (x);
}

const velocity::z_velocity_type& velocity::
z_velocity () const
{
  return this->z_velocity_.get ();
}

velocity::z_velocity_type& velocity::
z_velocity ()
{
  return this->z_velocity_.get ();
}

void velocity::
z_velocity (const z_velocity_type& x)
{
  this->z_velocity_.set (x);
}


// position
// 

const position::x_coordinate_type& position::
x_coordinate () const
{
  return this->x_coordinate_.get ();
}

position::x_coordinate_type& position::
x_coordinate ()
{
  return this->x_coordinate_.get ();
}

void position::
x_coordinate (const x_coordinate_type& x)
{
  this->x_coordinate_.set (x);
}

const position::y_coordinate_type& position::
y_coordinate () const
{
  return this->y_coordinate_.get ();
}

position::y_coordinate_type& position::
y_coordinate ()
{
  return this->y_coordinate_.get ();
}

void position::
y_coordinate (const y_coordinate_type& x)
{
  this->y_coordinate_.set (x);
}

const position::z_coordinate_type& position::
z_coordinate () const
{
  return this->z_coordinate_.get ();
}

position::z_coordinate_type& position::
z_coordinate ()
{
  return this->z_coordinate_.get ();
}

void position::
z_coordinate (const z_coordinate_type& x)
{
  this->z_coordinate_.set (x);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// Molsim_Input
//

Molsim_Input::
Molsim_Input (const Parameters_type& Parameters,
              const Particles_type& Particles)
: ::xml_schema::type (),
  Parameters_ (Parameters, this),
  Particles_ (Particles, this)
{
}

Molsim_Input::
Molsim_Input (::std::unique_ptr< Parameters_type > Parameters,
              ::std::unique_ptr< Particles_type > Particles)
: ::xml_schema::type (),
  Parameters_ (std::move (Parameters), this),
  Particles_ (std::move (Particles), this)
{
}

Molsim_Input::
Molsim_Input (const Molsim_Input& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  Parameters_ (x.Parameters_, f, this),
  Particles_ (x.Particles_, f, this)
{
}

Molsim_Input::
Molsim_Input (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  Parameters_ (this),
  Particles_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void Molsim_Input::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // Parameters
    //
    if (n.name () == "Parameters" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< Parameters_type > r (
        Parameters_traits::create (i, f, this));

      if (!Parameters_.present ())
      {
        this->Parameters_.set (::std::move (r));
        continue;
      }
    }

    // Particles
    //
    if (n.name () == "Particles" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< Particles_type > r (
        Particles_traits::create (i, f, this));

      if (!Particles_.present ())
      {
        this->Particles_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!Parameters_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Parameters",
      "");
  }

  if (!Particles_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Particles",
      "");
  }
}

Molsim_Input* Molsim_Input::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Molsim_Input (*this, f, c);
}

Molsim_Input& Molsim_Input::
operator= (const Molsim_Input& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->Parameters_ = x.Parameters_;
    this->Particles_ = x.Particles_;
  }

  return *this;
}

Molsim_Input::
~Molsim_Input ()
{
}

// Parameters
//

const Parameters::writer_type Parameters::writer_default_value_ (
  "vtk");

const Parameters::force_type Parameters::force_default_value_ (
  "lennard-jones");

const Parameters::output_name_type Parameters::output_name_default_value_ (
  "MD_vtk");

Parameters::
Parameters (const delta_t_type& delta_t,
            const t_end_type& t_end,
            const box_size_type& box_size,
            const number_cells_type& number_cells,
            const boundary_conditions_type& boundary_conditions,
            const cutoff_type& cutoff,
            const writer_type& writer,
            const force_type& force,
            const output_name_type& output_name,
            const output_frequency_type& output_frequency)
: ::xml_schema::type (),
  delta_t_ (delta_t, this),
  t_end_ (t_end, this),
  box_size_ (box_size, this),
  number_cells_ (number_cells, this),
  boundary_conditions_ (boundary_conditions, this),
  cutoff_ (cutoff, this),
  writer_ (writer, this),
  force_ (force, this),
  output_name_ (output_name, this),
  output_frequency_ (output_frequency, this)
{
}

Parameters::
Parameters (const delta_t_type& delta_t,
            const t_end_type& t_end,
            ::std::unique_ptr< box_size_type > box_size,
            ::std::unique_ptr< number_cells_type > number_cells,
            ::std::unique_ptr< boundary_conditions_type > boundary_conditions,
            const cutoff_type& cutoff,
            const writer_type& writer,
            const force_type& force,
            const output_name_type& output_name,
            const output_frequency_type& output_frequency)
: ::xml_schema::type (),
  delta_t_ (delta_t, this),
  t_end_ (t_end, this),
  box_size_ (std::move (box_size), this),
  number_cells_ (std::move (number_cells), this),
  boundary_conditions_ (std::move (boundary_conditions), this),
  cutoff_ (cutoff, this),
  writer_ (writer, this),
  force_ (force, this),
  output_name_ (output_name, this),
  output_frequency_ (output_frequency, this)
{
}

Parameters::
Parameters (const Parameters& x,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  delta_t_ (x.delta_t_, f, this),
  t_end_ (x.t_end_, f, this),
  box_size_ (x.box_size_, f, this),
  number_cells_ (x.number_cells_, f, this),
  boundary_conditions_ (x.boundary_conditions_, f, this),
  cutoff_ (x.cutoff_, f, this),
  writer_ (x.writer_, f, this),
  force_ (x.force_, f, this),
  output_name_ (x.output_name_, f, this),
  output_frequency_ (x.output_frequency_, f, this)
{
}

Parameters::
Parameters (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  delta_t_ (this),
  t_end_ (this),
  box_size_ (this),
  number_cells_ (this),
  boundary_conditions_ (this),
  cutoff_ (this),
  writer_ (this),
  force_ (this),
  output_name_ (this),
  output_frequency_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void Parameters::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // delta_t
    //
    if (n.name () == "delta_t" && n.namespace_ ().empty ())
    {
      if (!delta_t_.present ())
      {
        this->delta_t_.set (delta_t_traits::create (i, f, this));
        continue;
      }
    }

    // t_end
    //
    if (n.name () == "t_end" && n.namespace_ ().empty ())
    {
      if (!t_end_.present ())
      {
        this->t_end_.set (t_end_traits::create (i, f, this));
        continue;
      }
    }

    // box_size
    //
    if (n.name () == "box_size" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< box_size_type > r (
        box_size_traits::create (i, f, this));

      if (!box_size_.present ())
      {
        this->box_size_.set (::std::move (r));
        continue;
      }
    }

    // number_cells
    //
    if (n.name () == "number_cells" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< number_cells_type > r (
        number_cells_traits::create (i, f, this));

      if (!number_cells_.present ())
      {
        this->number_cells_.set (::std::move (r));
        continue;
      }
    }

    // boundary_conditions
    //
    if (n.name () == "boundary_conditions" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< boundary_conditions_type > r (
        boundary_conditions_traits::create (i, f, this));

      if (!boundary_conditions_.present ())
      {
        this->boundary_conditions_.set (::std::move (r));
        continue;
      }
    }

    // cutoff
    //
    if (n.name () == "cutoff" && n.namespace_ ().empty ())
    {
      if (!cutoff_.present ())
      {
        this->cutoff_.set (cutoff_traits::create (i, f, this));
        continue;
      }
    }

    // writer
    //
    if (n.name () == "writer" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< writer_type > r (
        writer_traits::create (i, f, this));

      if (!writer_.present ())
      {
        this->writer_.set (::std::move (r));
        continue;
      }
    }

    // force
    //
    if (n.name () == "force" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< force_type > r (
        force_traits::create (i, f, this));

      if (!force_.present ())
      {
        this->force_.set (::std::move (r));
        continue;
      }
    }

    // output_name
    //
    if (n.name () == "output_name" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< output_name_type > r (
        output_name_traits::create (i, f, this));

      if (!output_name_.present ())
      {
        this->output_name_.set (::std::move (r));
        continue;
      }
    }

    // output_frequency
    //
    if (n.name () == "output_frequency" && n.namespace_ ().empty ())
    {
      if (!output_frequency_.present ())
      {
        this->output_frequency_.set (output_frequency_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!delta_t_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "delta_t",
      "");
  }

  if (!t_end_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "t_end",
      "");
  }

  if (!box_size_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "box_size",
      "");
  }

  if (!number_cells_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "number_cells",
      "");
  }

  if (!boundary_conditions_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "boundary_conditions",
      "");
  }

  if (!cutoff_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "cutoff",
      "");
  }

  if (!writer_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "writer",
      "");
  }

  if (!force_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "force",
      "");
  }

  if (!output_name_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "output_name",
      "");
  }

  if (!output_frequency_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "output_frequency",
      "");
  }
}

Parameters* Parameters::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Parameters (*this, f, c);
}

Parameters& Parameters::
operator= (const Parameters& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->delta_t_ = x.delta_t_;
    this->t_end_ = x.t_end_;
    this->box_size_ = x.box_size_;
    this->number_cells_ = x.number_cells_;
    this->boundary_conditions_ = x.boundary_conditions_;
    this->cutoff_ = x.cutoff_;
    this->writer_ = x.writer_;
    this->force_ = x.force_;
    this->output_name_ = x.output_name_;
    this->output_frequency_ = x.output_frequency_;
  }

  return *this;
}

Parameters::
~Parameters ()
{
}

// Particles
//

Particles::
Particles ()
: ::xml_schema::type (),
  cuboid_ (this),
  particle_ (this),
  disc_ (this)
{
}

Particles::
Particles (const Particles& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  cuboid_ (x.cuboid_, f, this),
  particle_ (x.particle_, f, this),
  disc_ (x.disc_, f, this)
{
}

Particles::
Particles (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  cuboid_ (this),
  particle_ (this),
  disc_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void Particles::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // cuboid
    //
    if (n.name () == "cuboid" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< cuboid_type > r (
        cuboid_traits::create (i, f, this));

      this->cuboid_.push_back (::std::move (r));
      continue;
    }

    // particle
    //
    if (n.name () == "particle" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< particle_type > r (
        particle_traits::create (i, f, this));

      this->particle_.push_back (::std::move (r));
      continue;
    }

    // disc
    //
    if (n.name () == "disc" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< disc_type > r (
        disc_traits::create (i, f, this));

      this->disc_.push_back (::std::move (r));
      continue;
    }

    break;
  }
}

Particles* Particles::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class Particles (*this, f, c);
}

Particles& Particles::
operator= (const Particles& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->cuboid_ = x.cuboid_;
    this->particle_ = x.particle_;
    this->disc_ = x.disc_;
  }

  return *this;
}

Particles::
~Particles ()
{
}

// box_size
//

box_size::
box_size (const x_size_type& x_size,
          const y_size_type& y_size,
          const z_size_type& z_size)
: ::xml_schema::type (),
  x_size_ (x_size, this),
  y_size_ (y_size, this),
  z_size_ (z_size, this)
{
}

box_size::
box_size (const box_size& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_size_ (x.x_size_, f, this),
  y_size_ (x.y_size_, f, this),
  z_size_ (x.z_size_, f, this)
{
}

box_size::
box_size (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_size_ (this),
  y_size_ (this),
  z_size_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void box_size::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x-size
    //
    if (n.name () == "x-size" && n.namespace_ ().empty ())
    {
      if (!x_size_.present ())
      {
        this->x_size_.set (x_size_traits::create (i, f, this));
        continue;
      }
    }

    // y-size
    //
    if (n.name () == "y-size" && n.namespace_ ().empty ())
    {
      if (!y_size_.present ())
      {
        this->y_size_.set (y_size_traits::create (i, f, this));
        continue;
      }
    }

    // z-size
    //
    if (n.name () == "z-size" && n.namespace_ ().empty ())
    {
      if (!z_size_.present ())
      {
        this->z_size_.set (z_size_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!x_size_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x-size",
      "");
  }

  if (!y_size_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y-size",
      "");
  }

  if (!z_size_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z-size",
      "");
  }
}

box_size* box_size::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class box_size (*this, f, c);
}

box_size& box_size::
operator= (const box_size& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_size_ = x.x_size_;
    this->y_size_ = x.y_size_;
    this->z_size_ = x.z_size_;
  }

  return *this;
}

box_size::
~box_size ()
{
}

// number_cells
//

number_cells::
number_cells (const x_number_type& x_number,
              const y_number_type& y_number,
              const z_number_type& z_number)
: ::xml_schema::type (),
  x_number_ (x_number, this),
  y_number_ (y_number, this),
  z_number_ (z_number, this)
{
}

number_cells::
number_cells (const number_cells& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_number_ (x.x_number_, f, this),
  y_number_ (x.y_number_, f, this),
  z_number_ (x.z_number_, f, this)
{
}

number_cells::
number_cells (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_number_ (this),
  y_number_ (this),
  z_number_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void number_cells::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x-number
    //
    if (n.name () == "x-number" && n.namespace_ ().empty ())
    {
      if (!x_number_.present ())
      {
        this->x_number_.set (x_number_traits::create (i, f, this));
        continue;
      }
    }

    // y-number
    //
    if (n.name () == "y-number" && n.namespace_ ().empty ())
    {
      if (!y_number_.present ())
      {
        this->y_number_.set (y_number_traits::create (i, f, this));
        continue;
      }
    }

    // z-number
    //
    if (n.name () == "z-number" && n.namespace_ ().empty ())
    {
      if (!z_number_.present ())
      {
        this->z_number_.set (z_number_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!x_number_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x-number",
      "");
  }

  if (!y_number_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y-number",
      "");
  }

  if (!z_number_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z-number",
      "");
  }
}

number_cells* number_cells::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class number_cells (*this, f, c);
}

number_cells& number_cells::
operator= (const number_cells& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_number_ = x.x_number_;
    this->y_number_ = x.y_number_;
    this->z_number_ = x.z_number_;
  }

  return *this;
}

number_cells::
~number_cells ()
{
}

// boundary_conditions
//

const boundary_conditions::top_bound_type boundary_conditions::top_bound_default_value_ (
  "out");

const boundary_conditions::right_bound_type boundary_conditions::right_bound_default_value_ (
  "out");

const boundary_conditions::bottom_bound_type boundary_conditions::bottom_bound_default_value_ (
  "out");

const boundary_conditions::left_bound_type boundary_conditions::left_bound_default_value_ (
  "out");

boundary_conditions::
boundary_conditions (const top_bound_type& top_bound,
                     const right_bound_type& right_bound,
                     const bottom_bound_type& bottom_bound,
                     const left_bound_type& left_bound)
: ::xml_schema::type (),
  top_bound_ (top_bound, this),
  right_bound_ (right_bound, this),
  bottom_bound_ (bottom_bound, this),
  left_bound_ (left_bound, this)
{
}

boundary_conditions::
boundary_conditions (const boundary_conditions& x,
                     ::xml_schema::flags f,
                     ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  top_bound_ (x.top_bound_, f, this),
  right_bound_ (x.right_bound_, f, this),
  bottom_bound_ (x.bottom_bound_, f, this),
  left_bound_ (x.left_bound_, f, this)
{
}

boundary_conditions::
boundary_conditions (const ::xercesc::DOMElement& e,
                     ::xml_schema::flags f,
                     ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  top_bound_ (this),
  right_bound_ (this),
  bottom_bound_ (this),
  left_bound_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void boundary_conditions::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // top_bound
    //
    if (n.name () == "top_bound" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< top_bound_type > r (
        top_bound_traits::create (i, f, this));

      if (!top_bound_.present ())
      {
        this->top_bound_.set (::std::move (r));
        continue;
      }
    }

    // right_bound
    //
    if (n.name () == "right_bound" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< right_bound_type > r (
        right_bound_traits::create (i, f, this));

      if (!right_bound_.present ())
      {
        this->right_bound_.set (::std::move (r));
        continue;
      }
    }

    // bottom_bound
    //
    if (n.name () == "bottom_bound" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< bottom_bound_type > r (
        bottom_bound_traits::create (i, f, this));

      if (!bottom_bound_.present ())
      {
        this->bottom_bound_.set (::std::move (r));
        continue;
      }
    }

    // left_bound
    //
    if (n.name () == "left_bound" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< left_bound_type > r (
        left_bound_traits::create (i, f, this));

      if (!left_bound_.present ())
      {
        this->left_bound_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!top_bound_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "top_bound",
      "");
  }

  if (!right_bound_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "right_bound",
      "");
  }

  if (!bottom_bound_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "bottom_bound",
      "");
  }

  if (!left_bound_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "left_bound",
      "");
  }
}

boundary_conditions* boundary_conditions::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class boundary_conditions (*this, f, c);
}

boundary_conditions& boundary_conditions::
operator= (const boundary_conditions& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->top_bound_ = x.top_bound_;
    this->right_bound_ = x.right_bound_;
    this->bottom_bound_ = x.bottom_bound_;
    this->left_bound_ = x.left_bound_;
  }

  return *this;
}

boundary_conditions::
~boundary_conditions ()
{
}

// cuboid
//

cuboid::
cuboid (const base_coordinates_type& base_coordinates,
        const number_particles_type& number_particles,
        const velocity_type& velocity,
        const spacing_type& spacing,
        const mass_type& mass,
        const brownian_vel_type& brownian_vel)
: ::xml_schema::type (),
  base_coordinates_ (base_coordinates, this),
  number_particles_ (number_particles, this),
  velocity_ (velocity, this),
  spacing_ (spacing, this),
  mass_ (mass, this),
  brownian_vel_ (brownian_vel, this)
{
}

cuboid::
cuboid (::std::unique_ptr< base_coordinates_type > base_coordinates,
        ::std::unique_ptr< number_particles_type > number_particles,
        ::std::unique_ptr< velocity_type > velocity,
        const spacing_type& spacing,
        const mass_type& mass,
        const brownian_vel_type& brownian_vel)
: ::xml_schema::type (),
  base_coordinates_ (std::move (base_coordinates), this),
  number_particles_ (std::move (number_particles), this),
  velocity_ (std::move (velocity), this),
  spacing_ (spacing, this),
  mass_ (mass, this),
  brownian_vel_ (brownian_vel, this)
{
}

cuboid::
cuboid (const cuboid& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  base_coordinates_ (x.base_coordinates_, f, this),
  number_particles_ (x.number_particles_, f, this),
  velocity_ (x.velocity_, f, this),
  spacing_ (x.spacing_, f, this),
  mass_ (x.mass_, f, this),
  brownian_vel_ (x.brownian_vel_, f, this)
{
}

cuboid::
cuboid (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  base_coordinates_ (this),
  number_particles_ (this),
  velocity_ (this),
  spacing_ (this),
  mass_ (this),
  brownian_vel_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void cuboid::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // base_coordinates
    //
    if (n.name () == "base_coordinates" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< base_coordinates_type > r (
        base_coordinates_traits::create (i, f, this));

      if (!base_coordinates_.present ())
      {
        this->base_coordinates_.set (::std::move (r));
        continue;
      }
    }

    // number_particles
    //
    if (n.name () == "number_particles" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< number_particles_type > r (
        number_particles_traits::create (i, f, this));

      if (!number_particles_.present ())
      {
        this->number_particles_.set (::std::move (r));
        continue;
      }
    }

    // velocity
    //
    if (n.name () == "velocity" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< velocity_type > r (
        velocity_traits::create (i, f, this));

      if (!velocity_.present ())
      {
        this->velocity_.set (::std::move (r));
        continue;
      }
    }

    // spacing
    //
    if (n.name () == "spacing" && n.namespace_ ().empty ())
    {
      if (!spacing_.present ())
      {
        this->spacing_.set (spacing_traits::create (i, f, this));
        continue;
      }
    }

    // mass
    //
    if (n.name () == "mass" && n.namespace_ ().empty ())
    {
      if (!mass_.present ())
      {
        this->mass_.set (mass_traits::create (i, f, this));
        continue;
      }
    }

    // brownian_vel
    //
    if (n.name () == "brownian_vel" && n.namespace_ ().empty ())
    {
      if (!brownian_vel_.present ())
      {
        this->brownian_vel_.set (brownian_vel_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!base_coordinates_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "base_coordinates",
      "");
  }

  if (!number_particles_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "number_particles",
      "");
  }

  if (!velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "velocity",
      "");
  }

  if (!spacing_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "spacing",
      "");
  }

  if (!mass_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "mass",
      "");
  }

  if (!brownian_vel_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "brownian_vel",
      "");
  }
}

cuboid* cuboid::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class cuboid (*this, f, c);
}

cuboid& cuboid::
operator= (const cuboid& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->base_coordinates_ = x.base_coordinates_;
    this->number_particles_ = x.number_particles_;
    this->velocity_ = x.velocity_;
    this->spacing_ = x.spacing_;
    this->mass_ = x.mass_;
    this->brownian_vel_ = x.brownian_vel_;
  }

  return *this;
}

cuboid::
~cuboid ()
{
}

// particle
//

particle::
particle (const position_type& position,
          const velocity_type& velocity,
          const mass_type& mass)
: ::xml_schema::type (),
  position_ (position, this),
  velocity_ (velocity, this),
  mass_ (mass, this)
{
}

particle::
particle (::std::unique_ptr< position_type > position,
          ::std::unique_ptr< velocity_type > velocity,
          const mass_type& mass)
: ::xml_schema::type (),
  position_ (std::move (position), this),
  velocity_ (std::move (velocity), this),
  mass_ (mass, this)
{
}

particle::
particle (const particle& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  position_ (x.position_, f, this),
  velocity_ (x.velocity_, f, this),
  mass_ (x.mass_, f, this)
{
}

particle::
particle (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  position_ (this),
  velocity_ (this),
  mass_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void particle::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // position
    //
    if (n.name () == "position" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< position_type > r (
        position_traits::create (i, f, this));

      if (!position_.present ())
      {
        this->position_.set (::std::move (r));
        continue;
      }
    }

    // velocity
    //
    if (n.name () == "velocity" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< velocity_type > r (
        velocity_traits::create (i, f, this));

      if (!velocity_.present ())
      {
        this->velocity_.set (::std::move (r));
        continue;
      }
    }

    // mass
    //
    if (n.name () == "mass" && n.namespace_ ().empty ())
    {
      if (!mass_.present ())
      {
        this->mass_.set (mass_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!position_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "position",
      "");
  }

  if (!velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "velocity",
      "");
  }

  if (!mass_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "mass",
      "");
  }
}

particle* particle::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class particle (*this, f, c);
}

particle& particle::
operator= (const particle& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->position_ = x.position_;
    this->velocity_ = x.velocity_;
    this->mass_ = x.mass_;
  }

  return *this;
}

particle::
~particle ()
{
}

// disc
//

disc::
disc (const position_type& position,
      const velocity_type& velocity,
      const radius_type& radius,
      const mass_type& mass,
      const spacing_type& spacing,
      const brownian_vel_type& brownian_vel)
: ::xml_schema::type (),
  position_ (position, this),
  velocity_ (velocity, this),
  radius_ (radius, this),
  mass_ (mass, this),
  spacing_ (spacing, this),
  brownian_vel_ (brownian_vel, this)
{
}

disc::
disc (::std::unique_ptr< position_type > position,
      ::std::unique_ptr< velocity_type > velocity,
      const radius_type& radius,
      const mass_type& mass,
      const spacing_type& spacing,
      const brownian_vel_type& brownian_vel)
: ::xml_schema::type (),
  position_ (std::move (position), this),
  velocity_ (std::move (velocity), this),
  radius_ (radius, this),
  mass_ (mass, this),
  spacing_ (spacing, this),
  brownian_vel_ (brownian_vel, this)
{
}

disc::
disc (const disc& x,
      ::xml_schema::flags f,
      ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  position_ (x.position_, f, this),
  velocity_ (x.velocity_, f, this),
  radius_ (x.radius_, f, this),
  mass_ (x.mass_, f, this),
  spacing_ (x.spacing_, f, this),
  brownian_vel_ (x.brownian_vel_, f, this)
{
}

disc::
disc (const ::xercesc::DOMElement& e,
      ::xml_schema::flags f,
      ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  position_ (this),
  velocity_ (this),
  radius_ (this),
  mass_ (this),
  spacing_ (this),
  brownian_vel_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void disc::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // position
    //
    if (n.name () == "position" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< position_type > r (
        position_traits::create (i, f, this));

      if (!position_.present ())
      {
        this->position_.set (::std::move (r));
        continue;
      }
    }

    // velocity
    //
    if (n.name () == "velocity" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< velocity_type > r (
        velocity_traits::create (i, f, this));

      if (!velocity_.present ())
      {
        this->velocity_.set (::std::move (r));
        continue;
      }
    }

    // radius
    //
    if (n.name () == "radius" && n.namespace_ ().empty ())
    {
      if (!radius_.present ())
      {
        this->radius_.set (radius_traits::create (i, f, this));
        continue;
      }
    }

    // mass
    //
    if (n.name () == "mass" && n.namespace_ ().empty ())
    {
      if (!mass_.present ())
      {
        this->mass_.set (mass_traits::create (i, f, this));
        continue;
      }
    }

    // spacing
    //
    if (n.name () == "spacing" && n.namespace_ ().empty ())
    {
      if (!spacing_.present ())
      {
        this->spacing_.set (spacing_traits::create (i, f, this));
        continue;
      }
    }

    // brownian_vel
    //
    if (n.name () == "brownian_vel" && n.namespace_ ().empty ())
    {
      if (!brownian_vel_.present ())
      {
        this->brownian_vel_.set (brownian_vel_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!position_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "position",
      "");
  }

  if (!velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "velocity",
      "");
  }

  if (!radius_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "radius",
      "");
  }

  if (!mass_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "mass",
      "");
  }

  if (!spacing_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "spacing",
      "");
  }

  if (!brownian_vel_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "brownian_vel",
      "");
  }
}

disc* disc::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class disc (*this, f, c);
}

disc& disc::
operator= (const disc& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->position_ = x.position_;
    this->velocity_ = x.velocity_;
    this->radius_ = x.radius_;
    this->mass_ = x.mass_;
    this->spacing_ = x.spacing_;
    this->brownian_vel_ = x.brownian_vel_;
  }

  return *this;
}

disc::
~disc ()
{
}

// base_coordinates
//

base_coordinates::
base_coordinates (const x_coordinate_type& x_coordinate,
                  const y_coordinate_type& y_coordinate,
                  const z_coordinate_type& z_coordinate)
: ::xml_schema::type (),
  x_coordinate_ (x_coordinate, this),
  y_coordinate_ (y_coordinate, this),
  z_coordinate_ (z_coordinate, this)
{
}

base_coordinates::
base_coordinates (const base_coordinates& x,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_coordinate_ (x.x_coordinate_, f, this),
  y_coordinate_ (x.y_coordinate_, f, this),
  z_coordinate_ (x.z_coordinate_, f, this)
{
}

base_coordinates::
base_coordinates (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_coordinate_ (this),
  y_coordinate_ (this),
  z_coordinate_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void base_coordinates::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x-coordinate
    //
    if (n.name () == "x-coordinate" && n.namespace_ ().empty ())
    {
      if (!x_coordinate_.present ())
      {
        this->x_coordinate_.set (x_coordinate_traits::create (i, f, this));
        continue;
      }
    }

    // y-coordinate
    //
    if (n.name () == "y-coordinate" && n.namespace_ ().empty ())
    {
      if (!y_coordinate_.present ())
      {
        this->y_coordinate_.set (y_coordinate_traits::create (i, f, this));
        continue;
      }
    }

    // z-coordinate
    //
    if (n.name () == "z-coordinate" && n.namespace_ ().empty ())
    {
      if (!z_coordinate_.present ())
      {
        this->z_coordinate_.set (z_coordinate_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!x_coordinate_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x-coordinate",
      "");
  }

  if (!y_coordinate_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y-coordinate",
      "");
  }

  if (!z_coordinate_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z-coordinate",
      "");
  }
}

base_coordinates* base_coordinates::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class base_coordinates (*this, f, c);
}

base_coordinates& base_coordinates::
operator= (const base_coordinates& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_coordinate_ = x.x_coordinate_;
    this->y_coordinate_ = x.y_coordinate_;
    this->z_coordinate_ = x.z_coordinate_;
  }

  return *this;
}

base_coordinates::
~base_coordinates ()
{
}

// number_particles
//

number_particles::
number_particles (const x_number_type& x_number,
                  const y_number_type& y_number,
                  const z_number_type& z_number)
: ::xml_schema::type (),
  x_number_ (x_number, this),
  y_number_ (y_number, this),
  z_number_ (z_number, this)
{
}

number_particles::
number_particles (const number_particles& x,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_number_ (x.x_number_, f, this),
  y_number_ (x.y_number_, f, this),
  z_number_ (x.z_number_, f, this)
{
}

number_particles::
number_particles (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_number_ (this),
  y_number_ (this),
  z_number_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void number_particles::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x-number
    //
    if (n.name () == "x-number" && n.namespace_ ().empty ())
    {
      if (!x_number_.present ())
      {
        this->x_number_.set (x_number_traits::create (i, f, this));
        continue;
      }
    }

    // y-number
    //
    if (n.name () == "y-number" && n.namespace_ ().empty ())
    {
      if (!y_number_.present ())
      {
        this->y_number_.set (y_number_traits::create (i, f, this));
        continue;
      }
    }

    // z-number
    //
    if (n.name () == "z-number" && n.namespace_ ().empty ())
    {
      if (!z_number_.present ())
      {
        this->z_number_.set (z_number_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!x_number_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x-number",
      "");
  }

  if (!y_number_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y-number",
      "");
  }

  if (!z_number_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z-number",
      "");
  }
}

number_particles* number_particles::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class number_particles (*this, f, c);
}

number_particles& number_particles::
operator= (const number_particles& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_number_ = x.x_number_;
    this->y_number_ = x.y_number_;
    this->z_number_ = x.z_number_;
  }

  return *this;
}

number_particles::
~number_particles ()
{
}

// velocity
//

velocity::
velocity (const x_velocity_type& x_velocity,
          const y_velocity_type& y_velocity,
          const z_velocity_type& z_velocity)
: ::xml_schema::type (),
  x_velocity_ (x_velocity, this),
  y_velocity_ (y_velocity, this),
  z_velocity_ (z_velocity, this)
{
}

velocity::
velocity (const velocity& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_velocity_ (x.x_velocity_, f, this),
  y_velocity_ (x.y_velocity_, f, this),
  z_velocity_ (x.z_velocity_, f, this)
{
}

velocity::
velocity (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_velocity_ (this),
  y_velocity_ (this),
  z_velocity_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void velocity::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x-velocity
    //
    if (n.name () == "x-velocity" && n.namespace_ ().empty ())
    {
      if (!x_velocity_.present ())
      {
        this->x_velocity_.set (x_velocity_traits::create (i, f, this));
        continue;
      }
    }

    // y-velocity
    //
    if (n.name () == "y-velocity" && n.namespace_ ().empty ())
    {
      if (!y_velocity_.present ())
      {
        this->y_velocity_.set (y_velocity_traits::create (i, f, this));
        continue;
      }
    }

    // z-velocity
    //
    if (n.name () == "z-velocity" && n.namespace_ ().empty ())
    {
      if (!z_velocity_.present ())
      {
        this->z_velocity_.set (z_velocity_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!x_velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x-velocity",
      "");
  }

  if (!y_velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y-velocity",
      "");
  }

  if (!z_velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z-velocity",
      "");
  }
}

velocity* velocity::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class velocity (*this, f, c);
}

velocity& velocity::
operator= (const velocity& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_velocity_ = x.x_velocity_;
    this->y_velocity_ = x.y_velocity_;
    this->z_velocity_ = x.z_velocity_;
  }

  return *this;
}

velocity::
~velocity ()
{
}

// position
//

position::
position (const x_coordinate_type& x_coordinate,
          const y_coordinate_type& y_coordinate,
          const z_coordinate_type& z_coordinate)
: ::xml_schema::type (),
  x_coordinate_ (x_coordinate, this),
  y_coordinate_ (y_coordinate, this),
  z_coordinate_ (z_coordinate, this)
{
}

position::
position (const position& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_coordinate_ (x.x_coordinate_, f, this),
  y_coordinate_ (x.y_coordinate_, f, this),
  z_coordinate_ (x.z_coordinate_, f, this)
{
}

position::
position (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_coordinate_ (this),
  y_coordinate_ (this),
  z_coordinate_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void position::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x-coordinate
    //
    if (n.name () == "x-coordinate" && n.namespace_ ().empty ())
    {
      if (!x_coordinate_.present ())
      {
        this->x_coordinate_.set (x_coordinate_traits::create (i, f, this));
        continue;
      }
    }

    // y-coordinate
    //
    if (n.name () == "y-coordinate" && n.namespace_ ().empty ())
    {
      if (!y_coordinate_.present ())
      {
        this->y_coordinate_.set (y_coordinate_traits::create (i, f, this));
        continue;
      }
    }

    // z-coordinate
    //
    if (n.name () == "z-coordinate" && n.namespace_ ().empty ())
    {
      if (!z_coordinate_.present ())
      {
        this->z_coordinate_.set (z_coordinate_traits::create (i, f, this));
        continue;
      }
    }

    break;
  }

  if (!x_coordinate_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x-coordinate",
      "");
  }

  if (!y_coordinate_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y-coordinate",
      "");
  }

  if (!z_coordinate_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z-coordinate",
      "");
  }
}

position* position::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class position (*this, f, c);
}

position& position::
operator= (const position& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_coordinate_ = x.x_coordinate_;
    this->y_coordinate_ = x.y_coordinate_;
    this->z_coordinate_ = x.z_coordinate_;
  }

  return *this;
}

position::
~position ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (const ::std::string& u,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Molsim_Input > (
    ::Molsim_Input_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (const ::std::string& u,
               ::xml_schema::error_handler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Molsim_Input > (
    ::Molsim_Input_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (const ::std::string& u,
               ::xercesc::DOMErrorHandler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Molsim_Input > (
    ::Molsim_Input_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::std::istream& is,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Molsim_Input_ (isrc, f, p);
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::std::istream& is,
               ::xml_schema::error_handler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Molsim_Input_ (isrc, h, f, p);
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::std::istream& is,
               ::xercesc::DOMErrorHandler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Molsim_Input_ (isrc, h, f, p);
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::std::istream& is,
               const ::std::string& sid,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Molsim_Input_ (isrc, f, p);
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::std::istream& is,
               const ::std::string& sid,
               ::xml_schema::error_handler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Molsim_Input_ (isrc, h, f, p);
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::std::istream& is,
               const ::std::string& sid,
               ::xercesc::DOMErrorHandler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Molsim_Input_ (isrc, h, f, p);
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::xercesc::InputSource& i,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Molsim_Input > (
    ::Molsim_Input_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::xercesc::InputSource& i,
               ::xml_schema::error_handler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Molsim_Input > (
    ::Molsim_Input_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::xercesc::InputSource& i,
               ::xercesc::DOMErrorHandler& h,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Molsim_Input > (
    ::Molsim_Input_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (const ::xercesc::DOMDocument& doc,
               ::xml_schema::flags f,
               const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::Molsim_Input > (
      ::Molsim_Input_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "Molsim_Input" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Molsim_Input > r (
      ::xsd::cxx::tree::traits< ::Molsim_Input, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Molsim_Input",
    "");
}

::std::unique_ptr< ::Molsim_Input >
Molsim_Input_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
               ::xml_schema::flags f,
               const ::xml_schema::properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "Molsim_Input" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Molsim_Input > r (
      ::xsd::cxx::tree::traits< ::Molsim_Input, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Molsim_Input",
    "");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

void
Molsim_Input_ (::std::ostream& o,
               const ::Molsim_Input& s,
               const ::xml_schema::namespace_infomap& m,
               const ::std::string& e,
               ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Molsim_Input_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
Molsim_Input_ (::std::ostream& o,
               const ::Molsim_Input& s,
               ::xml_schema::error_handler& h,
               const ::xml_schema::namespace_infomap& m,
               const ::std::string& e,
               ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Molsim_Input_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Molsim_Input_ (::std::ostream& o,
               const ::Molsim_Input& s,
               ::xercesc::DOMErrorHandler& h,
               const ::xml_schema::namespace_infomap& m,
               const ::std::string& e,
               ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Molsim_Input_ (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Molsim_Input_ (::xercesc::XMLFormatTarget& t,
               const ::Molsim_Input& s,
               const ::xml_schema::namespace_infomap& m,
               const ::std::string& e,
               ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Molsim_Input_ (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
Molsim_Input_ (::xercesc::XMLFormatTarget& t,
               const ::Molsim_Input& s,
               ::xml_schema::error_handler& h,
               const ::xml_schema::namespace_infomap& m,
               const ::std::string& e,
               ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Molsim_Input_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Molsim_Input_ (::xercesc::XMLFormatTarget& t,
               const ::Molsim_Input& s,
               ::xercesc::DOMErrorHandler& h,
               const ::xml_schema::namespace_infomap& m,
               const ::std::string& e,
               ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::Molsim_Input_ (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
Molsim_Input_ (::xercesc::DOMDocument& d,
               const ::Molsim_Input& s,
               ::xml_schema::flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "Molsim_Input" &&
      n.namespace_ () == "")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "Molsim_Input",
      "");
  }
}

::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
Molsim_Input_ (const ::Molsim_Input& s,
               const ::xml_schema::namespace_infomap& m,
               ::xml_schema::flags f)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "Molsim_Input",
      "",
      m, f));

  ::Molsim_Input_ (*d, s, f);
  return d;
}

void
operator<< (::xercesc::DOMElement& e, const Molsim_Input& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // Parameters
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "Parameters",
        e));

    s << i.Parameters ();
  }

  // Particles
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "Particles",
        e));

    s << i.Particles ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const Parameters& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // delta_t
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "delta_t",
        e));

    s << ::xml_schema::as_decimal(i.delta_t ());
  }

  // t_end
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "t_end",
        e));

    s << ::xml_schema::as_decimal(i.t_end ());
  }

  // box_size
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "box_size",
        e));

    s << i.box_size ();
  }

  // number_cells
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "number_cells",
        e));

    s << i.number_cells ();
  }

  // boundary_conditions
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "boundary_conditions",
        e));

    s << i.boundary_conditions ();
  }

  // cutoff
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "cutoff",
        e));

    s << ::xml_schema::as_decimal(i.cutoff ());
  }

  // writer
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "writer",
        e));

    s << i.writer ();
  }

  // force
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "force",
        e));

    s << i.force ();
  }

  // output_name
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "output_name",
        e));

    s << i.output_name ();
  }

  // output_frequency
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "output_frequency",
        e));

    s << i.output_frequency ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const Particles& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // cuboid
  //
  for (Particles::cuboid_const_iterator
       b (i.cuboid ().begin ()), n (i.cuboid ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "cuboid",
        e));

    s << *b;
  }

  // particle
  //
  for (Particles::particle_const_iterator
       b (i.particle ().begin ()), n (i.particle ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "particle",
        e));

    s << *b;
  }

  // disc
  //
  for (Particles::disc_const_iterator
       b (i.disc ().begin ()), n (i.disc ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "disc",
        e));

    s << *b;
  }
}

void
operator<< (::xercesc::DOMElement& e, const box_size& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // x-size
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "x-size",
        e));

    s << ::xml_schema::as_decimal(i.x_size ());
  }

  // y-size
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "y-size",
        e));

    s << ::xml_schema::as_decimal(i.y_size ());
  }

  // z-size
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "z-size",
        e));

    s << ::xml_schema::as_decimal(i.z_size ());
  }
}

void
operator<< (::xercesc::DOMElement& e, const number_cells& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // x-number
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "x-number",
        e));

    s << i.x_number ();
  }

  // y-number
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "y-number",
        e));

    s << i.y_number ();
  }

  // z-number
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "z-number",
        e));

    s << i.z_number ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const boundary_conditions& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // top_bound
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "top_bound",
        e));

    s << i.top_bound ();
  }

  // right_bound
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "right_bound",
        e));

    s << i.right_bound ();
  }

  // bottom_bound
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "bottom_bound",
        e));

    s << i.bottom_bound ();
  }

  // left_bound
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "left_bound",
        e));

    s << i.left_bound ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const cuboid& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // base_coordinates
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "base_coordinates",
        e));

    s << i.base_coordinates ();
  }

  // number_particles
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "number_particles",
        e));

    s << i.number_particles ();
  }

  // velocity
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "velocity",
        e));

    s << i.velocity ();
  }

  // spacing
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "spacing",
        e));

    s << ::xml_schema::as_decimal(i.spacing ());
  }

  // mass
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "mass",
        e));

    s << ::xml_schema::as_decimal(i.mass ());
  }

  // brownian_vel
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "brownian_vel",
        e));

    s << ::xml_schema::as_decimal(i.brownian_vel ());
  }
}

void
operator<< (::xercesc::DOMElement& e, const particle& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // position
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "position",
        e));

    s << i.position ();
  }

  // velocity
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "velocity",
        e));

    s << i.velocity ();
  }

  // mass
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "mass",
        e));

    s << ::xml_schema::as_decimal(i.mass ());
  }
}

void
operator<< (::xercesc::DOMElement& e, const disc& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // position
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "position",
        e));

    s << i.position ();
  }

  // velocity
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "velocity",
        e));

    s << i.velocity ();
  }

  // radius
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "radius",
        e));

    s << i.radius ();
  }

  // mass
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "mass",
        e));

    s << ::xml_schema::as_decimal(i.mass ());
  }

  // spacing
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "spacing",
        e));

    s << ::xml_schema::as_decimal(i.spacing ());
  }

  // brownian_vel
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "brownian_vel",
        e));

    s << ::xml_schema::as_decimal(i.brownian_vel ());
  }
}

void
operator<< (::xercesc::DOMElement& e, const base_coordinates& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // x-coordinate
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "x-coordinate",
        e));

    s << ::xml_schema::as_decimal(i.x_coordinate ());
  }

  // y-coordinate
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "y-coordinate",
        e));

    s << ::xml_schema::as_decimal(i.y_coordinate ());
  }

  // z-coordinate
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "z-coordinate",
        e));

    s << ::xml_schema::as_decimal(i.z_coordinate ());
  }
}

void
operator<< (::xercesc::DOMElement& e, const number_particles& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // x-number
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "x-number",
        e));

    s << i.x_number ();
  }

  // y-number
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "y-number",
        e));

    s << i.y_number ();
  }

  // z-number
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "z-number",
        e));

    s << i.z_number ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const velocity& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // x-velocity
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "x-velocity",
        e));

    s << ::xml_schema::as_decimal(i.x_velocity ());
  }

  // y-velocity
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "y-velocity",
        e));

    s << ::xml_schema::as_decimal(i.y_velocity ());
  }

  // z-velocity
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "z-velocity",
        e));

    s << ::xml_schema::as_decimal(i.z_velocity ());
  }
}

void
operator<< (::xercesc::DOMElement& e, const position& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // x-coordinate
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "x-coordinate",
        e));

    s << ::xml_schema::as_decimal(i.x_coordinate ());
  }

  // y-coordinate
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "y-coordinate",
        e));

    s << ::xml_schema::as_decimal(i.y_coordinate ());
  }

  // z-coordinate
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "z-coordinate",
        e));

    s << ::xml_schema::as_decimal(i.z_coordinate ());
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

